// This file is generated by rust-protobuf 2.24.1. Do not edit
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `definitions.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
// const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_24_1;

#[derive(PartialEq,Clone,Default)]
#[cfg_attr(feature = "with-serde", derive(::serde::Serialize, ::serde::Deserialize))]
pub struct CompletedCommand {
    // message fields
    pub stdout: ::std::vec::Vec<u8>,
    pub stderr: ::std::vec::Vec<u8>,
    pub was_successful: bool,
    // special fields
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub unknown_fields: ::protobuf::UnknownFields,
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a CompletedCommand {
    fn default() -> &'a CompletedCommand {
        <CompletedCommand as ::protobuf::Message>::default_instance()
    }
}

impl CompletedCommand {
    pub fn new() -> CompletedCommand {
        ::std::default::Default::default()
    }

    // bytes stdout = 1;


    pub fn get_stdout(&self) -> &[u8] {
        &self.stdout
    }
    pub fn clear_stdout(&mut self) {
        self.stdout.clear();
    }

    // Param is passed by value, moved
    pub fn set_stdout(&mut self, v: ::std::vec::Vec<u8>) {
        self.stdout = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_stdout(&mut self) -> &mut ::std::vec::Vec<u8> {
        &mut self.stdout
    }

    // Take field
    pub fn take_stdout(&mut self) -> ::std::vec::Vec<u8> {
        ::std::mem::replace(&mut self.stdout, ::std::vec::Vec::new())
    }

    // bytes stderr = 2;


    pub fn get_stderr(&self) -> &[u8] {
        &self.stderr
    }
    pub fn clear_stderr(&mut self) {
        self.stderr.clear();
    }

    // Param is passed by value, moved
    pub fn set_stderr(&mut self, v: ::std::vec::Vec<u8>) {
        self.stderr = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_stderr(&mut self) -> &mut ::std::vec::Vec<u8> {
        &mut self.stderr
    }

    // Take field
    pub fn take_stderr(&mut self) -> ::std::vec::Vec<u8> {
        ::std::mem::replace(&mut self.stderr, ::std::vec::Vec::new())
    }

    // bool was_successful = 3;


    pub fn get_was_successful(&self) -> bool {
        self.was_successful
    }
    pub fn clear_was_successful(&mut self) {
        self.was_successful = false;
    }

    // Param is passed by value, moved
    pub fn set_was_successful(&mut self, v: bool) {
        self.was_successful = v;
    }
}

impl ::protobuf::Message for CompletedCommand {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_bytes_into(wire_type, is, &mut self.stdout)?;
                },
                2 => {
                    ::protobuf::rt::read_singular_proto3_bytes_into(wire_type, is, &mut self.stderr)?;
                },
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_bool()?;
                    self.was_successful = tmp;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.stdout.is_empty() {
            my_size += ::protobuf::rt::bytes_size(1, &self.stdout);
        }
        if !self.stderr.is_empty() {
            my_size += ::protobuf::rt::bytes_size(2, &self.stderr);
        }
        if self.was_successful != false {
            my_size += 2;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.stdout.is_empty() {
            os.write_bytes(1, &self.stdout)?;
        }
        if !self.stderr.is_empty() {
            os.write_bytes(2, &self.stderr)?;
        }
        if self.was_successful != false {
            os.write_bool(3, self.was_successful)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> CompletedCommand {
        CompletedCommand::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                "stdout",
                |m: &CompletedCommand| { &m.stdout },
                |m: &mut CompletedCommand| { &mut m.stdout },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                "stderr",
                |m: &CompletedCommand| { &m.stderr },
                |m: &mut CompletedCommand| { &mut m.stderr },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBool>(
                "was_successful",
                |m: &CompletedCommand| { &m.was_successful },
                |m: &mut CompletedCommand| { &mut m.was_successful },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<CompletedCommand>(
                "CompletedCommand",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static CompletedCommand {
        static instance: ::protobuf::rt::LazyV2<CompletedCommand> = ::protobuf::rt::LazyV2::INIT;
        instance.get(CompletedCommand::new)
    }
}

impl ::protobuf::Clear for CompletedCommand {
    fn clear(&mut self) {
        self.stdout.clear();
        self.stderr.clear();
        self.was_successful = false;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for CompletedCommand {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for CompletedCommand {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
#[cfg_attr(feature = "with-serde", derive(::serde::Serialize, ::serde::Deserialize))]
pub struct UnexpectedError {
    // message fields
    pub description: ::std::string::String,
    // special fields
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub unknown_fields: ::protobuf::UnknownFields,
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a UnexpectedError {
    fn default() -> &'a UnexpectedError {
        <UnexpectedError as ::protobuf::Message>::default_instance()
    }
}

impl UnexpectedError {
    pub fn new() -> UnexpectedError {
        ::std::default::Default::default()
    }

    // string description = 1;


    pub fn get_description(&self) -> &str {
        &self.description
    }
    pub fn clear_description(&mut self) {
        self.description.clear();
    }

    // Param is passed by value, moved
    pub fn set_description(&mut self, v: ::std::string::String) {
        self.description = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_description(&mut self) -> &mut ::std::string::String {
        &mut self.description
    }

    // Take field
    pub fn take_description(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.description, ::std::string::String::new())
    }
}

impl ::protobuf::Message for UnexpectedError {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.description)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.description.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.description);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.description.is_empty() {
            os.write_string(1, &self.description)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> UnexpectedError {
        UnexpectedError::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "description",
                |m: &UnexpectedError| { &m.description },
                |m: &mut UnexpectedError| { &mut m.description },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<UnexpectedError>(
                "UnexpectedError",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static UnexpectedError {
        static instance: ::protobuf::rt::LazyV2<UnexpectedError> = ::protobuf::rt::LazyV2::INIT;
        instance.get(UnexpectedError::new)
    }
}

impl ::protobuf::Clear for UnexpectedError {
    fn clear(&mut self) {
        self.description.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for UnexpectedError {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for UnexpectedError {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
#[cfg_attr(feature = "with-serde", derive(::serde::Serialize, ::serde::Deserialize))]
pub struct FromServer {
    // message oneof groups
    pub inner: ::std::option::Option<FromServer_oneof_inner>,
    // special fields
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub unknown_fields: ::protobuf::UnknownFields,
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a FromServer {
    fn default() -> &'a FromServer {
        <FromServer as ::protobuf::Message>::default_instance()
    }
}

#[derive(Clone,PartialEq,Debug)]
#[cfg_attr(feature = "with-serde", derive(::serde::Serialize, ::serde::Deserialize))]
pub enum FromServer_oneof_inner {
    completed_command(CompletedCommand),
    unexpected_error(UnexpectedError),
}

impl FromServer {
    pub fn new() -> FromServer {
        ::std::default::Default::default()
    }

    // .CompletedCommand completed_command = 1;


    pub fn get_completed_command(&self) -> &CompletedCommand {
        match self.inner {
            ::std::option::Option::Some(FromServer_oneof_inner::completed_command(ref v)) => v,
            _ => <CompletedCommand as ::protobuf::Message>::default_instance(),
        }
    }
    pub fn clear_completed_command(&mut self) {
        self.inner = ::std::option::Option::None;
    }

    pub fn has_completed_command(&self) -> bool {
        match self.inner {
            ::std::option::Option::Some(FromServer_oneof_inner::completed_command(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_completed_command(&mut self, v: CompletedCommand) {
        self.inner = ::std::option::Option::Some(FromServer_oneof_inner::completed_command(v))
    }

    // Mutable pointer to the field.
    pub fn mut_completed_command(&mut self) -> &mut CompletedCommand {
        if let ::std::option::Option::Some(FromServer_oneof_inner::completed_command(_)) = self.inner {
        } else {
            self.inner = ::std::option::Option::Some(FromServer_oneof_inner::completed_command(CompletedCommand::new()));
        }
        match self.inner {
            ::std::option::Option::Some(FromServer_oneof_inner::completed_command(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_completed_command(&mut self) -> CompletedCommand {
        if self.has_completed_command() {
            match self.inner.take() {
                ::std::option::Option::Some(FromServer_oneof_inner::completed_command(v)) => v,
                _ => panic!(),
            }
        } else {
            CompletedCommand::new()
        }
    }

    // .UnexpectedError unexpected_error = 2;


    pub fn get_unexpected_error(&self) -> &UnexpectedError {
        match self.inner {
            ::std::option::Option::Some(FromServer_oneof_inner::unexpected_error(ref v)) => v,
            _ => <UnexpectedError as ::protobuf::Message>::default_instance(),
        }
    }
    pub fn clear_unexpected_error(&mut self) {
        self.inner = ::std::option::Option::None;
    }

    pub fn has_unexpected_error(&self) -> bool {
        match self.inner {
            ::std::option::Option::Some(FromServer_oneof_inner::unexpected_error(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_unexpected_error(&mut self, v: UnexpectedError) {
        self.inner = ::std::option::Option::Some(FromServer_oneof_inner::unexpected_error(v))
    }

    // Mutable pointer to the field.
    pub fn mut_unexpected_error(&mut self) -> &mut UnexpectedError {
        if let ::std::option::Option::Some(FromServer_oneof_inner::unexpected_error(_)) = self.inner {
        } else {
            self.inner = ::std::option::Option::Some(FromServer_oneof_inner::unexpected_error(UnexpectedError::new()));
        }
        match self.inner {
            ::std::option::Option::Some(FromServer_oneof_inner::unexpected_error(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_unexpected_error(&mut self) -> UnexpectedError {
        if self.has_unexpected_error() {
            match self.inner.take() {
                ::std::option::Option::Some(FromServer_oneof_inner::unexpected_error(v)) => v,
                _ => panic!(),
            }
        } else {
            UnexpectedError::new()
        }
    }
}

impl ::protobuf::Message for FromServer {
    fn is_initialized(&self) -> bool {
        if let Some(FromServer_oneof_inner::completed_command(ref v)) = self.inner {
            if !v.is_initialized() {
                return false;
            }
        }
        if let Some(FromServer_oneof_inner::unexpected_error(ref v)) = self.inner {
            if !v.is_initialized() {
                return false;
            }
        }
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.inner = ::std::option::Option::Some(FromServer_oneof_inner::completed_command(is.read_message()?));
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.inner = ::std::option::Option::Some(FromServer_oneof_inner::unexpected_error(is.read_message()?));
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let ::std::option::Option::Some(ref v) = self.inner {
            match v {
                &FromServer_oneof_inner::completed_command(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
                },
                &FromServer_oneof_inner::unexpected_error(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
                },
            };
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if let ::std::option::Option::Some(ref v) = self.inner {
            match v {
                &FromServer_oneof_inner::completed_command(ref v) => {
                    os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
                    os.write_raw_varint32(v.get_cached_size())?;
                    v.write_to_with_cached_sizes(os)?;
                },
                &FromServer_oneof_inner::unexpected_error(ref v) => {
                    os.write_tag(2, ::protobuf::wire_format::WireTypeLengthDelimited)?;
                    os.write_raw_varint32(v.get_cached_size())?;
                    v.write_to_with_cached_sizes(os)?;
                },
            };
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> FromServer {
        FromServer::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_singular_message_accessor::<_, CompletedCommand>(
                "completed_command",
                FromServer::has_completed_command,
                FromServer::get_completed_command,
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_message_accessor::<_, UnexpectedError>(
                "unexpected_error",
                FromServer::has_unexpected_error,
                FromServer::get_unexpected_error,
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<FromServer>(
                "FromServer",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static FromServer {
        static instance: ::protobuf::rt::LazyV2<FromServer> = ::protobuf::rt::LazyV2::INIT;
        instance.get(FromServer::new)
    }
}

impl ::protobuf::Clear for FromServer {
    fn clear(&mut self) {
        self.inner = ::std::option::Option::None;
        self.inner = ::std::option::Option::None;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for FromServer {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for FromServer {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
#[cfg_attr(feature = "with-serde", derive(::serde::Serialize, ::serde::Deserialize))]
pub struct SetRowIndexFilters {
    // message fields
    pub filters: ::std::string::String,
    // special fields
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub unknown_fields: ::protobuf::UnknownFields,
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a SetRowIndexFilters {
    fn default() -> &'a SetRowIndexFilters {
        <SetRowIndexFilters as ::protobuf::Message>::default_instance()
    }
}

impl SetRowIndexFilters {
    pub fn new() -> SetRowIndexFilters {
        ::std::default::Default::default()
    }

    // string filters = 1;


    pub fn get_filters(&self) -> &str {
        &self.filters
    }
    pub fn clear_filters(&mut self) {
        self.filters.clear();
    }

    // Param is passed by value, moved
    pub fn set_filters(&mut self, v: ::std::string::String) {
        self.filters = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_filters(&mut self) -> &mut ::std::string::String {
        &mut self.filters
    }

    // Take field
    pub fn take_filters(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.filters, ::std::string::String::new())
    }
}

impl ::protobuf::Message for SetRowIndexFilters {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.filters)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.filters.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.filters);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.filters.is_empty() {
            os.write_string(1, &self.filters)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> SetRowIndexFilters {
        SetRowIndexFilters::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "filters",
                |m: &SetRowIndexFilters| { &m.filters },
                |m: &mut SetRowIndexFilters| { &mut m.filters },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<SetRowIndexFilters>(
                "SetRowIndexFilters",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static SetRowIndexFilters {
        static instance: ::protobuf::rt::LazyV2<SetRowIndexFilters> = ::protobuf::rt::LazyV2::INIT;
        instance.get(SetRowIndexFilters::new)
    }
}

impl ::protobuf::Clear for SetRowIndexFilters {
    fn clear(&mut self) {
        self.filters.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for SetRowIndexFilters {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for SetRowIndexFilters {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
#[cfg_attr(feature = "with-serde", derive(::serde::Serialize, ::serde::Deserialize))]
pub struct SetRowRegexFilter {
    // message fields
    pub filter: ::std::string::String,
    // special fields
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub unknown_fields: ::protobuf::UnknownFields,
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a SetRowRegexFilter {
    fn default() -> &'a SetRowRegexFilter {
        <SetRowRegexFilter as ::protobuf::Message>::default_instance()
    }
}

impl SetRowRegexFilter {
    pub fn new() -> SetRowRegexFilter {
        ::std::default::Default::default()
    }

    // string filter = 1;


    pub fn get_filter(&self) -> &str {
        &self.filter
    }
    pub fn clear_filter(&mut self) {
        self.filter.clear();
    }

    // Param is passed by value, moved
    pub fn set_filter(&mut self, v: ::std::string::String) {
        self.filter = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_filter(&mut self) -> &mut ::std::string::String {
        &mut self.filter
    }

    // Take field
    pub fn take_filter(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.filter, ::std::string::String::new())
    }
}

impl ::protobuf::Message for SetRowRegexFilter {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.filter)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.filter.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.filter);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.filter.is_empty() {
            os.write_string(1, &self.filter)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> SetRowRegexFilter {
        SetRowRegexFilter::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "filter",
                |m: &SetRowRegexFilter| { &m.filter },
                |m: &mut SetRowRegexFilter| { &mut m.filter },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<SetRowRegexFilter>(
                "SetRowRegexFilter",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static SetRowRegexFilter {
        static instance: ::protobuf::rt::LazyV2<SetRowRegexFilter> = ::protobuf::rt::LazyV2::INIT;
        instance.get(SetRowRegexFilter::new)
    }
}

impl ::protobuf::Clear for SetRowRegexFilter {
    fn clear(&mut self) {
        self.filter.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for SetRowRegexFilter {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for SetRowRegexFilter {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
#[cfg_attr(feature = "with-serde", derive(::serde::Serialize, ::serde::Deserialize))]
pub struct SetRowSeparators {
    // message fields
    pub separators: ::protobuf::RepeatedField<::std::string::String>,
    // special fields
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub unknown_fields: ::protobuf::UnknownFields,
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a SetRowSeparators {
    fn default() -> &'a SetRowSeparators {
        <SetRowSeparators as ::protobuf::Message>::default_instance()
    }
}

impl SetRowSeparators {
    pub fn new() -> SetRowSeparators {
        ::std::default::Default::default()
    }

    // repeated string separators = 1;


    pub fn get_separators(&self) -> &[::std::string::String] {
        &self.separators
    }
    pub fn clear_separators(&mut self) {
        self.separators.clear();
    }

    // Param is passed by value, moved
    pub fn set_separators(&mut self, v: ::protobuf::RepeatedField<::std::string::String>) {
        self.separators = v;
    }

    // Mutable pointer to the field.
    pub fn mut_separators(&mut self) -> &mut ::protobuf::RepeatedField<::std::string::String> {
        &mut self.separators
    }

    // Take field
    pub fn take_separators(&mut self) -> ::protobuf::RepeatedField<::std::string::String> {
        ::std::mem::replace(&mut self.separators, ::protobuf::RepeatedField::new())
    }
}

impl ::protobuf::Message for SetRowSeparators {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_repeated_string_into(wire_type, is, &mut self.separators)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        for value in &self.separators {
            my_size += ::protobuf::rt::string_size(1, &value);
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        for v in &self.separators {
            os.write_string(1, &v)?;
        };
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> SetRowSeparators {
        SetRowSeparators::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "separators",
                |m: &SetRowSeparators| { &m.separators },
                |m: &mut SetRowSeparators| { &mut m.separators },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<SetRowSeparators>(
                "SetRowSeparators",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static SetRowSeparators {
        static instance: ::protobuf::rt::LazyV2<SetRowSeparators> = ::protobuf::rt::LazyV2::INIT;
        instance.get(SetRowSeparators::new)
    }
}

impl ::protobuf::Clear for SetRowSeparators {
    fn clear(&mut self) {
        self.separators.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for SetRowSeparators {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for SetRowSeparators {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
#[cfg_attr(feature = "with-serde", derive(::serde::Serialize, ::serde::Deserialize))]
pub struct SetColumnIndexFilters {
    // message fields
    pub filters: ::std::string::String,
    // special fields
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub unknown_fields: ::protobuf::UnknownFields,
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a SetColumnIndexFilters {
    fn default() -> &'a SetColumnIndexFilters {
        <SetColumnIndexFilters as ::protobuf::Message>::default_instance()
    }
}

impl SetColumnIndexFilters {
    pub fn new() -> SetColumnIndexFilters {
        ::std::default::Default::default()
    }

    // string filters = 1;


    pub fn get_filters(&self) -> &str {
        &self.filters
    }
    pub fn clear_filters(&mut self) {
        self.filters.clear();
    }

    // Param is passed by value, moved
    pub fn set_filters(&mut self, v: ::std::string::String) {
        self.filters = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_filters(&mut self) -> &mut ::std::string::String {
        &mut self.filters
    }

    // Take field
    pub fn take_filters(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.filters, ::std::string::String::new())
    }
}

impl ::protobuf::Message for SetColumnIndexFilters {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.filters)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.filters.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.filters);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.filters.is_empty() {
            os.write_string(1, &self.filters)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> SetColumnIndexFilters {
        SetColumnIndexFilters::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "filters",
                |m: &SetColumnIndexFilters| { &m.filters },
                |m: &mut SetColumnIndexFilters| { &mut m.filters },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<SetColumnIndexFilters>(
                "SetColumnIndexFilters",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static SetColumnIndexFilters {
        static instance: ::protobuf::rt::LazyV2<SetColumnIndexFilters> = ::protobuf::rt::LazyV2::INIT;
        instance.get(SetColumnIndexFilters::new)
    }
}

impl ::protobuf::Clear for SetColumnIndexFilters {
    fn clear(&mut self) {
        self.filters.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for SetColumnIndexFilters {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for SetColumnIndexFilters {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
#[cfg_attr(feature = "with-serde", derive(::serde::Serialize, ::serde::Deserialize))]
pub struct SetColumnRegexFilter {
    // message fields
    pub filter: ::std::string::String,
    // special fields
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub unknown_fields: ::protobuf::UnknownFields,
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a SetColumnRegexFilter {
    fn default() -> &'a SetColumnRegexFilter {
        <SetColumnRegexFilter as ::protobuf::Message>::default_instance()
    }
}

impl SetColumnRegexFilter {
    pub fn new() -> SetColumnRegexFilter {
        ::std::default::Default::default()
    }

    // string filter = 1;


    pub fn get_filter(&self) -> &str {
        &self.filter
    }
    pub fn clear_filter(&mut self) {
        self.filter.clear();
    }

    // Param is passed by value, moved
    pub fn set_filter(&mut self, v: ::std::string::String) {
        self.filter = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_filter(&mut self) -> &mut ::std::string::String {
        &mut self.filter
    }

    // Take field
    pub fn take_filter(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.filter, ::std::string::String::new())
    }
}

impl ::protobuf::Message for SetColumnRegexFilter {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.filter)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.filter.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.filter);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.filter.is_empty() {
            os.write_string(1, &self.filter)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> SetColumnRegexFilter {
        SetColumnRegexFilter::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "filter",
                |m: &SetColumnRegexFilter| { &m.filter },
                |m: &mut SetColumnRegexFilter| { &mut m.filter },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<SetColumnRegexFilter>(
                "SetColumnRegexFilter",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static SetColumnRegexFilter {
        static instance: ::protobuf::rt::LazyV2<SetColumnRegexFilter> = ::protobuf::rt::LazyV2::INIT;
        instance.get(SetColumnRegexFilter::new)
    }
}

impl ::protobuf::Clear for SetColumnRegexFilter {
    fn clear(&mut self) {
        self.filter.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for SetColumnRegexFilter {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for SetColumnRegexFilter {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
#[cfg_attr(feature = "with-serde", derive(::serde::Serialize, ::serde::Deserialize))]
pub struct SetColumnSeparators {
    // message fields
    pub separators: ::protobuf::RepeatedField<::std::string::String>,
    // special fields
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub unknown_fields: ::protobuf::UnknownFields,
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a SetColumnSeparators {
    fn default() -> &'a SetColumnSeparators {
        <SetColumnSeparators as ::protobuf::Message>::default_instance()
    }
}

impl SetColumnSeparators {
    pub fn new() -> SetColumnSeparators {
        ::std::default::Default::default()
    }

    // repeated string separators = 1;


    pub fn get_separators(&self) -> &[::std::string::String] {
        &self.separators
    }
    pub fn clear_separators(&mut self) {
        self.separators.clear();
    }

    // Param is passed by value, moved
    pub fn set_separators(&mut self, v: ::protobuf::RepeatedField<::std::string::String>) {
        self.separators = v;
    }

    // Mutable pointer to the field.
    pub fn mut_separators(&mut self) -> &mut ::protobuf::RepeatedField<::std::string::String> {
        &mut self.separators
    }

    // Take field
    pub fn take_separators(&mut self) -> ::protobuf::RepeatedField<::std::string::String> {
        ::std::mem::replace(&mut self.separators, ::protobuf::RepeatedField::new())
    }
}

impl ::protobuf::Message for SetColumnSeparators {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_repeated_string_into(wire_type, is, &mut self.separators)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        for value in &self.separators {
            my_size += ::protobuf::rt::string_size(1, &value);
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        for v in &self.separators {
            os.write_string(1, &v)?;
        };
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> SetColumnSeparators {
        SetColumnSeparators::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "separators",
                |m: &SetColumnSeparators| { &m.separators },
                |m: &mut SetColumnSeparators| { &mut m.separators },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<SetColumnSeparators>(
                "SetColumnSeparators",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static SetColumnSeparators {
        static instance: ::protobuf::rt::LazyV2<SetColumnSeparators> = ::protobuf::rt::LazyV2::INIT;
        instance.get(SetColumnSeparators::new)
    }
}

impl ::protobuf::Clear for SetColumnSeparators {
    fn clear(&mut self) {
        self.separators.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for SetColumnSeparators {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for SetColumnSeparators {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
#[cfg_attr(feature = "with-serde", derive(::serde::Serialize, ::serde::Deserialize))]
pub struct RunCommand {
    // message fields
    pub command: ::std::string::String,
    // special fields
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub unknown_fields: ::protobuf::UnknownFields,
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a RunCommand {
    fn default() -> &'a RunCommand {
        <RunCommand as ::protobuf::Message>::default_instance()
    }
}

impl RunCommand {
    pub fn new() -> RunCommand {
        ::std::default::Default::default()
    }

    // string command = 1;


    pub fn get_command(&self) -> &str {
        &self.command
    }
    pub fn clear_command(&mut self) {
        self.command.clear();
    }

    // Param is passed by value, moved
    pub fn set_command(&mut self, v: ::std::string::String) {
        self.command = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_command(&mut self) -> &mut ::std::string::String {
        &mut self.command
    }

    // Take field
    pub fn take_command(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.command, ::std::string::String::new())
    }
}

impl ::protobuf::Message for RunCommand {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.command)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.command.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.command);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.command.is_empty() {
            os.write_string(1, &self.command)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> RunCommand {
        RunCommand::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "command",
                |m: &RunCommand| { &m.command },
                |m: &mut RunCommand| { &mut m.command },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<RunCommand>(
                "RunCommand",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static RunCommand {
        static instance: ::protobuf::rt::LazyV2<RunCommand> = ::protobuf::rt::LazyV2::INIT;
        instance.get(RunCommand::new)
    }
}

impl ::protobuf::Clear for RunCommand {
    fn clear(&mut self) {
        self.command.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for RunCommand {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for RunCommand {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
#[cfg_attr(feature = "with-serde", derive(::serde::Serialize, ::serde::Deserialize))]
pub struct CancelCommand {
    // special fields
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub unknown_fields: ::protobuf::UnknownFields,
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a CancelCommand {
    fn default() -> &'a CancelCommand {
        <CancelCommand as ::protobuf::Message>::default_instance()
    }
}

impl CancelCommand {
    pub fn new() -> CancelCommand {
        ::std::default::Default::default()
    }
}

impl ::protobuf::Message for CancelCommand {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> CancelCommand {
        CancelCommand::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let fields = ::std::vec::Vec::new();
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<CancelCommand>(
                "CancelCommand",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static CancelCommand {
        static instance: ::protobuf::rt::LazyV2<CancelCommand> = ::protobuf::rt::LazyV2::INIT;
        instance.get(CancelCommand::new)
    }
}

impl ::protobuf::Clear for CancelCommand {
    fn clear(&mut self) {
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for CancelCommand {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for CancelCommand {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
#[cfg_attr(feature = "with-serde", derive(::serde::Serialize, ::serde::Deserialize))]
pub struct FromClient {
    // message oneof groups
    pub inner: ::std::option::Option<FromClient_oneof_inner>,
    // special fields
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub unknown_fields: ::protobuf::UnknownFields,
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a FromClient {
    fn default() -> &'a FromClient {
        <FromClient as ::protobuf::Message>::default_instance()
    }
}

#[derive(Clone,PartialEq,Debug)]
#[cfg_attr(feature = "with-serde", derive(::serde::Serialize, ::serde::Deserialize))]
pub enum FromClient_oneof_inner {
    set_row_index_filters(SetRowIndexFilters),
    set_row_regex_filter(SetRowRegexFilter),
    set_row_separators(SetRowSeparators),
    set_column_index_filters(SetColumnIndexFilters),
    set_column_regex_filter(SetColumnRegexFilter),
    set_column_separators(SetColumnSeparators),
    run_command(RunCommand),
    cancel_command(CancelCommand),
}

impl FromClient {
    pub fn new() -> FromClient {
        ::std::default::Default::default()
    }

    // .SetRowIndexFilters set_row_index_filters = 1;


    pub fn get_set_row_index_filters(&self) -> &SetRowIndexFilters {
        match self.inner {
            ::std::option::Option::Some(FromClient_oneof_inner::set_row_index_filters(ref v)) => v,
            _ => <SetRowIndexFilters as ::protobuf::Message>::default_instance(),
        }
    }
    pub fn clear_set_row_index_filters(&mut self) {
        self.inner = ::std::option::Option::None;
    }

    pub fn has_set_row_index_filters(&self) -> bool {
        match self.inner {
            ::std::option::Option::Some(FromClient_oneof_inner::set_row_index_filters(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_set_row_index_filters(&mut self, v: SetRowIndexFilters) {
        self.inner = ::std::option::Option::Some(FromClient_oneof_inner::set_row_index_filters(v))
    }

    // Mutable pointer to the field.
    pub fn mut_set_row_index_filters(&mut self) -> &mut SetRowIndexFilters {
        if let ::std::option::Option::Some(FromClient_oneof_inner::set_row_index_filters(_)) = self.inner {
        } else {
            self.inner = ::std::option::Option::Some(FromClient_oneof_inner::set_row_index_filters(SetRowIndexFilters::new()));
        }
        match self.inner {
            ::std::option::Option::Some(FromClient_oneof_inner::set_row_index_filters(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_set_row_index_filters(&mut self) -> SetRowIndexFilters {
        if self.has_set_row_index_filters() {
            match self.inner.take() {
                ::std::option::Option::Some(FromClient_oneof_inner::set_row_index_filters(v)) => v,
                _ => panic!(),
            }
        } else {
            SetRowIndexFilters::new()
        }
    }

    // .SetRowRegexFilter set_row_regex_filter = 2;


    pub fn get_set_row_regex_filter(&self) -> &SetRowRegexFilter {
        match self.inner {
            ::std::option::Option::Some(FromClient_oneof_inner::set_row_regex_filter(ref v)) => v,
            _ => <SetRowRegexFilter as ::protobuf::Message>::default_instance(),
        }
    }
    pub fn clear_set_row_regex_filter(&mut self) {
        self.inner = ::std::option::Option::None;
    }

    pub fn has_set_row_regex_filter(&self) -> bool {
        match self.inner {
            ::std::option::Option::Some(FromClient_oneof_inner::set_row_regex_filter(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_set_row_regex_filter(&mut self, v: SetRowRegexFilter) {
        self.inner = ::std::option::Option::Some(FromClient_oneof_inner::set_row_regex_filter(v))
    }

    // Mutable pointer to the field.
    pub fn mut_set_row_regex_filter(&mut self) -> &mut SetRowRegexFilter {
        if let ::std::option::Option::Some(FromClient_oneof_inner::set_row_regex_filter(_)) = self.inner {
        } else {
            self.inner = ::std::option::Option::Some(FromClient_oneof_inner::set_row_regex_filter(SetRowRegexFilter::new()));
        }
        match self.inner {
            ::std::option::Option::Some(FromClient_oneof_inner::set_row_regex_filter(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_set_row_regex_filter(&mut self) -> SetRowRegexFilter {
        if self.has_set_row_regex_filter() {
            match self.inner.take() {
                ::std::option::Option::Some(FromClient_oneof_inner::set_row_regex_filter(v)) => v,
                _ => panic!(),
            }
        } else {
            SetRowRegexFilter::new()
        }
    }

    // .SetRowSeparators set_row_separators = 3;


    pub fn get_set_row_separators(&self) -> &SetRowSeparators {
        match self.inner {
            ::std::option::Option::Some(FromClient_oneof_inner::set_row_separators(ref v)) => v,
            _ => <SetRowSeparators as ::protobuf::Message>::default_instance(),
        }
    }
    pub fn clear_set_row_separators(&mut self) {
        self.inner = ::std::option::Option::None;
    }

    pub fn has_set_row_separators(&self) -> bool {
        match self.inner {
            ::std::option::Option::Some(FromClient_oneof_inner::set_row_separators(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_set_row_separators(&mut self, v: SetRowSeparators) {
        self.inner = ::std::option::Option::Some(FromClient_oneof_inner::set_row_separators(v))
    }

    // Mutable pointer to the field.
    pub fn mut_set_row_separators(&mut self) -> &mut SetRowSeparators {
        if let ::std::option::Option::Some(FromClient_oneof_inner::set_row_separators(_)) = self.inner {
        } else {
            self.inner = ::std::option::Option::Some(FromClient_oneof_inner::set_row_separators(SetRowSeparators::new()));
        }
        match self.inner {
            ::std::option::Option::Some(FromClient_oneof_inner::set_row_separators(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_set_row_separators(&mut self) -> SetRowSeparators {
        if self.has_set_row_separators() {
            match self.inner.take() {
                ::std::option::Option::Some(FromClient_oneof_inner::set_row_separators(v)) => v,
                _ => panic!(),
            }
        } else {
            SetRowSeparators::new()
        }
    }

    // .SetColumnIndexFilters set_column_index_filters = 4;


    pub fn get_set_column_index_filters(&self) -> &SetColumnIndexFilters {
        match self.inner {
            ::std::option::Option::Some(FromClient_oneof_inner::set_column_index_filters(ref v)) => v,
            _ => <SetColumnIndexFilters as ::protobuf::Message>::default_instance(),
        }
    }
    pub fn clear_set_column_index_filters(&mut self) {
        self.inner = ::std::option::Option::None;
    }

    pub fn has_set_column_index_filters(&self) -> bool {
        match self.inner {
            ::std::option::Option::Some(FromClient_oneof_inner::set_column_index_filters(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_set_column_index_filters(&mut self, v: SetColumnIndexFilters) {
        self.inner = ::std::option::Option::Some(FromClient_oneof_inner::set_column_index_filters(v))
    }

    // Mutable pointer to the field.
    pub fn mut_set_column_index_filters(&mut self) -> &mut SetColumnIndexFilters {
        if let ::std::option::Option::Some(FromClient_oneof_inner::set_column_index_filters(_)) = self.inner {
        } else {
            self.inner = ::std::option::Option::Some(FromClient_oneof_inner::set_column_index_filters(SetColumnIndexFilters::new()));
        }
        match self.inner {
            ::std::option::Option::Some(FromClient_oneof_inner::set_column_index_filters(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_set_column_index_filters(&mut self) -> SetColumnIndexFilters {
        if self.has_set_column_index_filters() {
            match self.inner.take() {
                ::std::option::Option::Some(FromClient_oneof_inner::set_column_index_filters(v)) => v,
                _ => panic!(),
            }
        } else {
            SetColumnIndexFilters::new()
        }
    }

    // .SetColumnRegexFilter set_column_regex_filter = 5;


    pub fn get_set_column_regex_filter(&self) -> &SetColumnRegexFilter {
        match self.inner {
            ::std::option::Option::Some(FromClient_oneof_inner::set_column_regex_filter(ref v)) => v,
            _ => <SetColumnRegexFilter as ::protobuf::Message>::default_instance(),
        }
    }
    pub fn clear_set_column_regex_filter(&mut self) {
        self.inner = ::std::option::Option::None;
    }

    pub fn has_set_column_regex_filter(&self) -> bool {
        match self.inner {
            ::std::option::Option::Some(FromClient_oneof_inner::set_column_regex_filter(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_set_column_regex_filter(&mut self, v: SetColumnRegexFilter) {
        self.inner = ::std::option::Option::Some(FromClient_oneof_inner::set_column_regex_filter(v))
    }

    // Mutable pointer to the field.
    pub fn mut_set_column_regex_filter(&mut self) -> &mut SetColumnRegexFilter {
        if let ::std::option::Option::Some(FromClient_oneof_inner::set_column_regex_filter(_)) = self.inner {
        } else {
            self.inner = ::std::option::Option::Some(FromClient_oneof_inner::set_column_regex_filter(SetColumnRegexFilter::new()));
        }
        match self.inner {
            ::std::option::Option::Some(FromClient_oneof_inner::set_column_regex_filter(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_set_column_regex_filter(&mut self) -> SetColumnRegexFilter {
        if self.has_set_column_regex_filter() {
            match self.inner.take() {
                ::std::option::Option::Some(FromClient_oneof_inner::set_column_regex_filter(v)) => v,
                _ => panic!(),
            }
        } else {
            SetColumnRegexFilter::new()
        }
    }

    // .SetColumnSeparators set_column_separators = 6;


    pub fn get_set_column_separators(&self) -> &SetColumnSeparators {
        match self.inner {
            ::std::option::Option::Some(FromClient_oneof_inner::set_column_separators(ref v)) => v,
            _ => <SetColumnSeparators as ::protobuf::Message>::default_instance(),
        }
    }
    pub fn clear_set_column_separators(&mut self) {
        self.inner = ::std::option::Option::None;
    }

    pub fn has_set_column_separators(&self) -> bool {
        match self.inner {
            ::std::option::Option::Some(FromClient_oneof_inner::set_column_separators(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_set_column_separators(&mut self, v: SetColumnSeparators) {
        self.inner = ::std::option::Option::Some(FromClient_oneof_inner::set_column_separators(v))
    }

    // Mutable pointer to the field.
    pub fn mut_set_column_separators(&mut self) -> &mut SetColumnSeparators {
        if let ::std::option::Option::Some(FromClient_oneof_inner::set_column_separators(_)) = self.inner {
        } else {
            self.inner = ::std::option::Option::Some(FromClient_oneof_inner::set_column_separators(SetColumnSeparators::new()));
        }
        match self.inner {
            ::std::option::Option::Some(FromClient_oneof_inner::set_column_separators(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_set_column_separators(&mut self) -> SetColumnSeparators {
        if self.has_set_column_separators() {
            match self.inner.take() {
                ::std::option::Option::Some(FromClient_oneof_inner::set_column_separators(v)) => v,
                _ => panic!(),
            }
        } else {
            SetColumnSeparators::new()
        }
    }

    // .RunCommand run_command = 7;


    pub fn get_run_command(&self) -> &RunCommand {
        match self.inner {
            ::std::option::Option::Some(FromClient_oneof_inner::run_command(ref v)) => v,
            _ => <RunCommand as ::protobuf::Message>::default_instance(),
        }
    }
    pub fn clear_run_command(&mut self) {
        self.inner = ::std::option::Option::None;
    }

    pub fn has_run_command(&self) -> bool {
        match self.inner {
            ::std::option::Option::Some(FromClient_oneof_inner::run_command(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_run_command(&mut self, v: RunCommand) {
        self.inner = ::std::option::Option::Some(FromClient_oneof_inner::run_command(v))
    }

    // Mutable pointer to the field.
    pub fn mut_run_command(&mut self) -> &mut RunCommand {
        if let ::std::option::Option::Some(FromClient_oneof_inner::run_command(_)) = self.inner {
        } else {
            self.inner = ::std::option::Option::Some(FromClient_oneof_inner::run_command(RunCommand::new()));
        }
        match self.inner {
            ::std::option::Option::Some(FromClient_oneof_inner::run_command(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_run_command(&mut self) -> RunCommand {
        if self.has_run_command() {
            match self.inner.take() {
                ::std::option::Option::Some(FromClient_oneof_inner::run_command(v)) => v,
                _ => panic!(),
            }
        } else {
            RunCommand::new()
        }
    }

    // .CancelCommand cancel_command = 8;


    pub fn get_cancel_command(&self) -> &CancelCommand {
        match self.inner {
            ::std::option::Option::Some(FromClient_oneof_inner::cancel_command(ref v)) => v,
            _ => <CancelCommand as ::protobuf::Message>::default_instance(),
        }
    }
    pub fn clear_cancel_command(&mut self) {
        self.inner = ::std::option::Option::None;
    }

    pub fn has_cancel_command(&self) -> bool {
        match self.inner {
            ::std::option::Option::Some(FromClient_oneof_inner::cancel_command(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_cancel_command(&mut self, v: CancelCommand) {
        self.inner = ::std::option::Option::Some(FromClient_oneof_inner::cancel_command(v))
    }

    // Mutable pointer to the field.
    pub fn mut_cancel_command(&mut self) -> &mut CancelCommand {
        if let ::std::option::Option::Some(FromClient_oneof_inner::cancel_command(_)) = self.inner {
        } else {
            self.inner = ::std::option::Option::Some(FromClient_oneof_inner::cancel_command(CancelCommand::new()));
        }
        match self.inner {
            ::std::option::Option::Some(FromClient_oneof_inner::cancel_command(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_cancel_command(&mut self) -> CancelCommand {
        if self.has_cancel_command() {
            match self.inner.take() {
                ::std::option::Option::Some(FromClient_oneof_inner::cancel_command(v)) => v,
                _ => panic!(),
            }
        } else {
            CancelCommand::new()
        }
    }
}

impl ::protobuf::Message for FromClient {
    fn is_initialized(&self) -> bool {
        if let Some(FromClient_oneof_inner::set_row_index_filters(ref v)) = self.inner {
            if !v.is_initialized() {
                return false;
            }
        }
        if let Some(FromClient_oneof_inner::set_row_regex_filter(ref v)) = self.inner {
            if !v.is_initialized() {
                return false;
            }
        }
        if let Some(FromClient_oneof_inner::set_row_separators(ref v)) = self.inner {
            if !v.is_initialized() {
                return false;
            }
        }
        if let Some(FromClient_oneof_inner::set_column_index_filters(ref v)) = self.inner {
            if !v.is_initialized() {
                return false;
            }
        }
        if let Some(FromClient_oneof_inner::set_column_regex_filter(ref v)) = self.inner {
            if !v.is_initialized() {
                return false;
            }
        }
        if let Some(FromClient_oneof_inner::set_column_separators(ref v)) = self.inner {
            if !v.is_initialized() {
                return false;
            }
        }
        if let Some(FromClient_oneof_inner::run_command(ref v)) = self.inner {
            if !v.is_initialized() {
                return false;
            }
        }
        if let Some(FromClient_oneof_inner::cancel_command(ref v)) = self.inner {
            if !v.is_initialized() {
                return false;
            }
        }
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.inner = ::std::option::Option::Some(FromClient_oneof_inner::set_row_index_filters(is.read_message()?));
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.inner = ::std::option::Option::Some(FromClient_oneof_inner::set_row_regex_filter(is.read_message()?));
                },
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.inner = ::std::option::Option::Some(FromClient_oneof_inner::set_row_separators(is.read_message()?));
                },
                4 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.inner = ::std::option::Option::Some(FromClient_oneof_inner::set_column_index_filters(is.read_message()?));
                },
                5 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.inner = ::std::option::Option::Some(FromClient_oneof_inner::set_column_regex_filter(is.read_message()?));
                },
                6 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.inner = ::std::option::Option::Some(FromClient_oneof_inner::set_column_separators(is.read_message()?));
                },
                7 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.inner = ::std::option::Option::Some(FromClient_oneof_inner::run_command(is.read_message()?));
                },
                8 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.inner = ::std::option::Option::Some(FromClient_oneof_inner::cancel_command(is.read_message()?));
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let ::std::option::Option::Some(ref v) = self.inner {
            match v {
                &FromClient_oneof_inner::set_row_index_filters(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
                },
                &FromClient_oneof_inner::set_row_regex_filter(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
                },
                &FromClient_oneof_inner::set_row_separators(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
                },
                &FromClient_oneof_inner::set_column_index_filters(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
                },
                &FromClient_oneof_inner::set_column_regex_filter(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
                },
                &FromClient_oneof_inner::set_column_separators(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
                },
                &FromClient_oneof_inner::run_command(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
                },
                &FromClient_oneof_inner::cancel_command(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
                },
            };
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if let ::std::option::Option::Some(ref v) = self.inner {
            match v {
                &FromClient_oneof_inner::set_row_index_filters(ref v) => {
                    os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
                    os.write_raw_varint32(v.get_cached_size())?;
                    v.write_to_with_cached_sizes(os)?;
                },
                &FromClient_oneof_inner::set_row_regex_filter(ref v) => {
                    os.write_tag(2, ::protobuf::wire_format::WireTypeLengthDelimited)?;
                    os.write_raw_varint32(v.get_cached_size())?;
                    v.write_to_with_cached_sizes(os)?;
                },
                &FromClient_oneof_inner::set_row_separators(ref v) => {
                    os.write_tag(3, ::protobuf::wire_format::WireTypeLengthDelimited)?;
                    os.write_raw_varint32(v.get_cached_size())?;
                    v.write_to_with_cached_sizes(os)?;
                },
                &FromClient_oneof_inner::set_column_index_filters(ref v) => {
                    os.write_tag(4, ::protobuf::wire_format::WireTypeLengthDelimited)?;
                    os.write_raw_varint32(v.get_cached_size())?;
                    v.write_to_with_cached_sizes(os)?;
                },
                &FromClient_oneof_inner::set_column_regex_filter(ref v) => {
                    os.write_tag(5, ::protobuf::wire_format::WireTypeLengthDelimited)?;
                    os.write_raw_varint32(v.get_cached_size())?;
                    v.write_to_with_cached_sizes(os)?;
                },
                &FromClient_oneof_inner::set_column_separators(ref v) => {
                    os.write_tag(6, ::protobuf::wire_format::WireTypeLengthDelimited)?;
                    os.write_raw_varint32(v.get_cached_size())?;
                    v.write_to_with_cached_sizes(os)?;
                },
                &FromClient_oneof_inner::run_command(ref v) => {
                    os.write_tag(7, ::protobuf::wire_format::WireTypeLengthDelimited)?;
                    os.write_raw_varint32(v.get_cached_size())?;
                    v.write_to_with_cached_sizes(os)?;
                },
                &FromClient_oneof_inner::cancel_command(ref v) => {
                    os.write_tag(8, ::protobuf::wire_format::WireTypeLengthDelimited)?;
                    os.write_raw_varint32(v.get_cached_size())?;
                    v.write_to_with_cached_sizes(os)?;
                },
            };
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> FromClient {
        FromClient::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_singular_message_accessor::<_, SetRowIndexFilters>(
                "set_row_index_filters",
                FromClient::has_set_row_index_filters,
                FromClient::get_set_row_index_filters,
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_message_accessor::<_, SetRowRegexFilter>(
                "set_row_regex_filter",
                FromClient::has_set_row_regex_filter,
                FromClient::get_set_row_regex_filter,
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_message_accessor::<_, SetRowSeparators>(
                "set_row_separators",
                FromClient::has_set_row_separators,
                FromClient::get_set_row_separators,
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_message_accessor::<_, SetColumnIndexFilters>(
                "set_column_index_filters",
                FromClient::has_set_column_index_filters,
                FromClient::get_set_column_index_filters,
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_message_accessor::<_, SetColumnRegexFilter>(
                "set_column_regex_filter",
                FromClient::has_set_column_regex_filter,
                FromClient::get_set_column_regex_filter,
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_message_accessor::<_, SetColumnSeparators>(
                "set_column_separators",
                FromClient::has_set_column_separators,
                FromClient::get_set_column_separators,
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_message_accessor::<_, RunCommand>(
                "run_command",
                FromClient::has_run_command,
                FromClient::get_run_command,
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_message_accessor::<_, CancelCommand>(
                "cancel_command",
                FromClient::has_cancel_command,
                FromClient::get_cancel_command,
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<FromClient>(
                "FromClient",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static FromClient {
        static instance: ::protobuf::rt::LazyV2<FromClient> = ::protobuf::rt::LazyV2::INIT;
        instance.get(FromClient::new)
    }
}

impl ::protobuf::Clear for FromClient {
    fn clear(&mut self) {
        self.inner = ::std::option::Option::None;
        self.inner = ::std::option::Option::None;
        self.inner = ::std::option::Option::None;
        self.inner = ::std::option::Option::None;
        self.inner = ::std::option::Option::None;
        self.inner = ::std::option::Option::None;
        self.inner = ::std::option::Option::None;
        self.inner = ::std::option::Option::None;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for FromClient {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for FromClient {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x11definitions.proto\"i\n\x10CompletedCommand\x12\x16\n\x06stdout\x18\
    \x01\x20\x01(\x0cR\x06stdout\x12\x16\n\x06stderr\x18\x02\x20\x01(\x0cR\
    \x06stderr\x12%\n\x0ewas_successful\x18\x03\x20\x01(\x08R\rwasSuccessful\
    \"3\n\x0fUnexpectedError\x12\x20\n\x0bdescription\x18\x01\x20\x01(\tR\
    \x0bdescription\"\x96\x01\n\nFromServer\x12@\n\x11completed_command\x18\
    \x01\x20\x01(\x0b2\x11.CompletedCommandH\0R\x10completedCommand\x12=\n\
    \x10unexpected_error\x18\x02\x20\x01(\x0b2\x10.UnexpectedErrorH\0R\x0fun\
    expectedErrorB\x07\n\x05inner\".\n\x12SetRowIndexFilters\x12\x18\n\x07fi\
    lters\x18\x01\x20\x01(\tR\x07filters\"+\n\x11SetRowRegexFilter\x12\x16\n\
    \x06filter\x18\x01\x20\x01(\tR\x06filter\"2\n\x10SetRowSeparators\x12\
    \x1e\n\nseparators\x18\x01\x20\x03(\tR\nseparators\"1\n\x15SetColumnInde\
    xFilters\x12\x18\n\x07filters\x18\x01\x20\x01(\tR\x07filters\".\n\x14Set\
    ColumnRegexFilter\x12\x16\n\x06filter\x18\x01\x20\x01(\tR\x06filter\"5\n\
    \x13SetColumnSeparators\x12\x1e\n\nseparators\x18\x01\x20\x03(\tR\nsepar\
    ators\"&\n\nRunCommand\x12\x18\n\x07command\x18\x01\x20\x01(\tR\x07comma\
    nd\"\x0f\n\rCancelCommand\"\xc1\x04\n\nFromClient\x12H\n\x15set_row_inde\
    x_filters\x18\x01\x20\x01(\x0b2\x13.SetRowIndexFiltersH\0R\x12setRowInde\
    xFilters\x12E\n\x14set_row_regex_filter\x18\x02\x20\x01(\x0b2\x12.SetRow\
    RegexFilterH\0R\x11setRowRegexFilter\x12A\n\x12set_row_separators\x18\
    \x03\x20\x01(\x0b2\x11.SetRowSeparatorsH\0R\x10setRowSeparators\x12Q\n\
    \x18set_column_index_filters\x18\x04\x20\x01(\x0b2\x16.SetColumnIndexFil\
    tersH\0R\x15setColumnIndexFilters\x12N\n\x17set_column_regex_filter\x18\
    \x05\x20\x01(\x0b2\x15.SetColumnRegexFilterH\0R\x14setColumnRegexFilter\
    \x12J\n\x15set_column_separators\x18\x06\x20\x01(\x0b2\x14.SetColumnSepa\
    ratorsH\0R\x13setColumnSeparators\x12.\n\x0brun_command\x18\x07\x20\x01(\
    \x0b2\x0b.RunCommandH\0R\nrunCommand\x127\n\x0ecancel_command\x18\x08\
    \x20\x01(\x0b2\x0e.CancelCommandH\0R\rcancelCommandB\x07\n\x05innerb\x06\
    proto3\
";

static file_descriptor_proto_lazy: ::protobuf::rt::LazyV2<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::LazyV2::INIT;

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    file_descriptor_proto_lazy.get(|| {
        parse_descriptor_proto()
    })
}
