// This file is generated by rust-protobuf 2.24.1. Do not edit
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `definitions.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
// const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_24_1;

#[derive(PartialEq,Clone,Default)]
#[cfg_attr(feature = "with-serde", derive(::serde::Serialize, ::serde::Deserialize))]
pub struct UnexpectedError {
    // message fields
    pub description: ::std::string::String,
    // special fields
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub unknown_fields: ::protobuf::UnknownFields,
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a UnexpectedError {
    fn default() -> &'a UnexpectedError {
        <UnexpectedError as ::protobuf::Message>::default_instance()
    }
}

impl UnexpectedError {
    pub fn new() -> UnexpectedError {
        ::std::default::Default::default()
    }

    // string description = 1;


    pub fn get_description(&self) -> &str {
        &self.description
    }
    pub fn clear_description(&mut self) {
        self.description.clear();
    }

    // Param is passed by value, moved
    pub fn set_description(&mut self, v: ::std::string::String) {
        self.description = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_description(&mut self) -> &mut ::std::string::String {
        &mut self.description
    }

    // Take field
    pub fn take_description(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.description, ::std::string::String::new())
    }
}

impl ::protobuf::Message for UnexpectedError {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.description)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.description.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.description);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.description.is_empty() {
            os.write_string(1, &self.description)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> UnexpectedError {
        UnexpectedError::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "description",
                |m: &UnexpectedError| { &m.description },
                |m: &mut UnexpectedError| { &mut m.description },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<UnexpectedError>(
                "UnexpectedError",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static UnexpectedError {
        static instance: ::protobuf::rt::LazyV2<UnexpectedError> = ::protobuf::rt::LazyV2::INIT;
        instance.get(UnexpectedError::new)
    }
}

impl ::protobuf::Clear for UnexpectedError {
    fn clear(&mut self) {
        self.description.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for UnexpectedError {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for UnexpectedError {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
#[cfg_attr(feature = "with-serde", derive(::serde::Serialize, ::serde::Deserialize))]
pub struct FromServer {
    // message oneof groups
    pub inner: ::std::option::Option<FromServer_oneof_inner>,
    // special fields
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub unknown_fields: ::protobuf::UnknownFields,
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a FromServer {
    fn default() -> &'a FromServer {
        <FromServer as ::protobuf::Message>::default_instance()
    }
}

#[derive(Clone,PartialEq,Debug)]
#[cfg_attr(feature = "with-serde", derive(::serde::Serialize, ::serde::Deserialize))]
pub enum FromServer_oneof_inner {
    output(::std::vec::Vec<u8>),
    unexpected_error(UnexpectedError),
}

impl FromServer {
    pub fn new() -> FromServer {
        ::std::default::Default::default()
    }

    // bytes output = 1;


    pub fn get_output(&self) -> &[u8] {
        match self.inner {
            ::std::option::Option::Some(FromServer_oneof_inner::output(ref v)) => v,
            _ => &[],
        }
    }
    pub fn clear_output(&mut self) {
        self.inner = ::std::option::Option::None;
    }

    pub fn has_output(&self) -> bool {
        match self.inner {
            ::std::option::Option::Some(FromServer_oneof_inner::output(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_output(&mut self, v: ::std::vec::Vec<u8>) {
        self.inner = ::std::option::Option::Some(FromServer_oneof_inner::output(v))
    }

    // Mutable pointer to the field.
    pub fn mut_output(&mut self) -> &mut ::std::vec::Vec<u8> {
        if let ::std::option::Option::Some(FromServer_oneof_inner::output(_)) = self.inner {
        } else {
            self.inner = ::std::option::Option::Some(FromServer_oneof_inner::output(::std::vec::Vec::new()));
        }
        match self.inner {
            ::std::option::Option::Some(FromServer_oneof_inner::output(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_output(&mut self) -> ::std::vec::Vec<u8> {
        if self.has_output() {
            match self.inner.take() {
                ::std::option::Option::Some(FromServer_oneof_inner::output(v)) => v,
                _ => panic!(),
            }
        } else {
            ::std::vec::Vec::new()
        }
    }

    // .UnexpectedError unexpected_error = 2;


    pub fn get_unexpected_error(&self) -> &UnexpectedError {
        match self.inner {
            ::std::option::Option::Some(FromServer_oneof_inner::unexpected_error(ref v)) => v,
            _ => <UnexpectedError as ::protobuf::Message>::default_instance(),
        }
    }
    pub fn clear_unexpected_error(&mut self) {
        self.inner = ::std::option::Option::None;
    }

    pub fn has_unexpected_error(&self) -> bool {
        match self.inner {
            ::std::option::Option::Some(FromServer_oneof_inner::unexpected_error(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_unexpected_error(&mut self, v: UnexpectedError) {
        self.inner = ::std::option::Option::Some(FromServer_oneof_inner::unexpected_error(v))
    }

    // Mutable pointer to the field.
    pub fn mut_unexpected_error(&mut self) -> &mut UnexpectedError {
        if let ::std::option::Option::Some(FromServer_oneof_inner::unexpected_error(_)) = self.inner {
        } else {
            self.inner = ::std::option::Option::Some(FromServer_oneof_inner::unexpected_error(UnexpectedError::new()));
        }
        match self.inner {
            ::std::option::Option::Some(FromServer_oneof_inner::unexpected_error(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_unexpected_error(&mut self) -> UnexpectedError {
        if self.has_unexpected_error() {
            match self.inner.take() {
                ::std::option::Option::Some(FromServer_oneof_inner::unexpected_error(v)) => v,
                _ => panic!(),
            }
        } else {
            UnexpectedError::new()
        }
    }
}

impl ::protobuf::Message for FromServer {
    fn is_initialized(&self) -> bool {
        if let Some(FromServer_oneof_inner::unexpected_error(ref v)) = self.inner {
            if !v.is_initialized() {
                return false;
            }
        }
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.inner = ::std::option::Option::Some(FromServer_oneof_inner::output(is.read_bytes()?));
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.inner = ::std::option::Option::Some(FromServer_oneof_inner::unexpected_error(is.read_message()?));
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let ::std::option::Option::Some(ref v) = self.inner {
            match v {
                &FromServer_oneof_inner::output(ref v) => {
                    my_size += ::protobuf::rt::bytes_size(1, &v);
                },
                &FromServer_oneof_inner::unexpected_error(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
                },
            };
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if let ::std::option::Option::Some(ref v) = self.inner {
            match v {
                &FromServer_oneof_inner::output(ref v) => {
                    os.write_bytes(1, v)?;
                },
                &FromServer_oneof_inner::unexpected_error(ref v) => {
                    os.write_tag(2, ::protobuf::wire_format::WireTypeLengthDelimited)?;
                    os.write_raw_varint32(v.get_cached_size())?;
                    v.write_to_with_cached_sizes(os)?;
                },
            };
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> FromServer {
        FromServer::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_singular_bytes_accessor::<_>(
                "output",
                FromServer::has_output,
                FromServer::get_output,
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_message_accessor::<_, UnexpectedError>(
                "unexpected_error",
                FromServer::has_unexpected_error,
                FromServer::get_unexpected_error,
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<FromServer>(
                "FromServer",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static FromServer {
        static instance: ::protobuf::rt::LazyV2<FromServer> = ::protobuf::rt::LazyV2::INIT;
        instance.get(FromServer::new)
    }
}

impl ::protobuf::Clear for FromServer {
    fn clear(&mut self) {
        self.inner = ::std::option::Option::None;
        self.inner = ::std::option::Option::None;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for FromServer {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for FromServer {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
#[cfg_attr(feature = "with-serde", derive(::serde::Serialize, ::serde::Deserialize))]
pub struct Initialize {
    // message fields
    pub row_index_filters: ::std::string::String,
    pub row_regex_filter: ::std::string::String,
    pub row_separators: ::protobuf::RepeatedField<::std::string::String>,
    pub column_index_filters: ::std::string::String,
    pub column_regex_filter: ::std::string::String,
    pub column_separators: ::protobuf::RepeatedField<::std::string::String>,
    // special fields
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub unknown_fields: ::protobuf::UnknownFields,
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a Initialize {
    fn default() -> &'a Initialize {
        <Initialize as ::protobuf::Message>::default_instance()
    }
}

impl Initialize {
    pub fn new() -> Initialize {
        ::std::default::Default::default()
    }

    // string row_index_filters = 1;


    pub fn get_row_index_filters(&self) -> &str {
        &self.row_index_filters
    }
    pub fn clear_row_index_filters(&mut self) {
        self.row_index_filters.clear();
    }

    // Param is passed by value, moved
    pub fn set_row_index_filters(&mut self, v: ::std::string::String) {
        self.row_index_filters = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_row_index_filters(&mut self) -> &mut ::std::string::String {
        &mut self.row_index_filters
    }

    // Take field
    pub fn take_row_index_filters(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.row_index_filters, ::std::string::String::new())
    }

    // string row_regex_filter = 2;


    pub fn get_row_regex_filter(&self) -> &str {
        &self.row_regex_filter
    }
    pub fn clear_row_regex_filter(&mut self) {
        self.row_regex_filter.clear();
    }

    // Param is passed by value, moved
    pub fn set_row_regex_filter(&mut self, v: ::std::string::String) {
        self.row_regex_filter = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_row_regex_filter(&mut self) -> &mut ::std::string::String {
        &mut self.row_regex_filter
    }

    // Take field
    pub fn take_row_regex_filter(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.row_regex_filter, ::std::string::String::new())
    }

    // repeated string row_separators = 3;


    pub fn get_row_separators(&self) -> &[::std::string::String] {
        &self.row_separators
    }
    pub fn clear_row_separators(&mut self) {
        self.row_separators.clear();
    }

    // Param is passed by value, moved
    pub fn set_row_separators(&mut self, v: ::protobuf::RepeatedField<::std::string::String>) {
        self.row_separators = v;
    }

    // Mutable pointer to the field.
    pub fn mut_row_separators(&mut self) -> &mut ::protobuf::RepeatedField<::std::string::String> {
        &mut self.row_separators
    }

    // Take field
    pub fn take_row_separators(&mut self) -> ::protobuf::RepeatedField<::std::string::String> {
        ::std::mem::replace(&mut self.row_separators, ::protobuf::RepeatedField::new())
    }

    // string column_index_filters = 4;


    pub fn get_column_index_filters(&self) -> &str {
        &self.column_index_filters
    }
    pub fn clear_column_index_filters(&mut self) {
        self.column_index_filters.clear();
    }

    // Param is passed by value, moved
    pub fn set_column_index_filters(&mut self, v: ::std::string::String) {
        self.column_index_filters = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_column_index_filters(&mut self) -> &mut ::std::string::String {
        &mut self.column_index_filters
    }

    // Take field
    pub fn take_column_index_filters(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.column_index_filters, ::std::string::String::new())
    }

    // string column_regex_filter = 5;


    pub fn get_column_regex_filter(&self) -> &str {
        &self.column_regex_filter
    }
    pub fn clear_column_regex_filter(&mut self) {
        self.column_regex_filter.clear();
    }

    // Param is passed by value, moved
    pub fn set_column_regex_filter(&mut self, v: ::std::string::String) {
        self.column_regex_filter = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_column_regex_filter(&mut self) -> &mut ::std::string::String {
        &mut self.column_regex_filter
    }

    // Take field
    pub fn take_column_regex_filter(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.column_regex_filter, ::std::string::String::new())
    }

    // repeated string column_separators = 6;


    pub fn get_column_separators(&self) -> &[::std::string::String] {
        &self.column_separators
    }
    pub fn clear_column_separators(&mut self) {
        self.column_separators.clear();
    }

    // Param is passed by value, moved
    pub fn set_column_separators(&mut self, v: ::protobuf::RepeatedField<::std::string::String>) {
        self.column_separators = v;
    }

    // Mutable pointer to the field.
    pub fn mut_column_separators(&mut self) -> &mut ::protobuf::RepeatedField<::std::string::String> {
        &mut self.column_separators
    }

    // Take field
    pub fn take_column_separators(&mut self) -> ::protobuf::RepeatedField<::std::string::String> {
        ::std::mem::replace(&mut self.column_separators, ::protobuf::RepeatedField::new())
    }
}

impl ::protobuf::Message for Initialize {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.row_index_filters)?;
                },
                2 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.row_regex_filter)?;
                },
                3 => {
                    ::protobuf::rt::read_repeated_string_into(wire_type, is, &mut self.row_separators)?;
                },
                4 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.column_index_filters)?;
                },
                5 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.column_regex_filter)?;
                },
                6 => {
                    ::protobuf::rt::read_repeated_string_into(wire_type, is, &mut self.column_separators)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.row_index_filters.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.row_index_filters);
        }
        if !self.row_regex_filter.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.row_regex_filter);
        }
        for value in &self.row_separators {
            my_size += ::protobuf::rt::string_size(3, &value);
        };
        if !self.column_index_filters.is_empty() {
            my_size += ::protobuf::rt::string_size(4, &self.column_index_filters);
        }
        if !self.column_regex_filter.is_empty() {
            my_size += ::protobuf::rt::string_size(5, &self.column_regex_filter);
        }
        for value in &self.column_separators {
            my_size += ::protobuf::rt::string_size(6, &value);
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.row_index_filters.is_empty() {
            os.write_string(1, &self.row_index_filters)?;
        }
        if !self.row_regex_filter.is_empty() {
            os.write_string(2, &self.row_regex_filter)?;
        }
        for v in &self.row_separators {
            os.write_string(3, &v)?;
        };
        if !self.column_index_filters.is_empty() {
            os.write_string(4, &self.column_index_filters)?;
        }
        if !self.column_regex_filter.is_empty() {
            os.write_string(5, &self.column_regex_filter)?;
        }
        for v in &self.column_separators {
            os.write_string(6, &v)?;
        };
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> Initialize {
        Initialize::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "row_index_filters",
                |m: &Initialize| { &m.row_index_filters },
                |m: &mut Initialize| { &mut m.row_index_filters },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "row_regex_filter",
                |m: &Initialize| { &m.row_regex_filter },
                |m: &mut Initialize| { &mut m.row_regex_filter },
            ));
            fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "row_separators",
                |m: &Initialize| { &m.row_separators },
                |m: &mut Initialize| { &mut m.row_separators },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "column_index_filters",
                |m: &Initialize| { &m.column_index_filters },
                |m: &mut Initialize| { &mut m.column_index_filters },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "column_regex_filter",
                |m: &Initialize| { &m.column_regex_filter },
                |m: &mut Initialize| { &mut m.column_regex_filter },
            ));
            fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "column_separators",
                |m: &Initialize| { &m.column_separators },
                |m: &mut Initialize| { &mut m.column_separators },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<Initialize>(
                "Initialize",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static Initialize {
        static instance: ::protobuf::rt::LazyV2<Initialize> = ::protobuf::rt::LazyV2::INIT;
        instance.get(Initialize::new)
    }
}

impl ::protobuf::Clear for Initialize {
    fn clear(&mut self) {
        self.row_index_filters.clear();
        self.row_regex_filter.clear();
        self.row_separators.clear();
        self.column_index_filters.clear();
        self.column_regex_filter.clear();
        self.column_separators.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for Initialize {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Initialize {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
#[cfg_attr(feature = "with-serde", derive(::serde::Serialize, ::serde::Deserialize))]
pub struct SetRowIndexFilters {
    // message fields
    pub filters: ::std::string::String,
    // special fields
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub unknown_fields: ::protobuf::UnknownFields,
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a SetRowIndexFilters {
    fn default() -> &'a SetRowIndexFilters {
        <SetRowIndexFilters as ::protobuf::Message>::default_instance()
    }
}

impl SetRowIndexFilters {
    pub fn new() -> SetRowIndexFilters {
        ::std::default::Default::default()
    }

    // string filters = 1;


    pub fn get_filters(&self) -> &str {
        &self.filters
    }
    pub fn clear_filters(&mut self) {
        self.filters.clear();
    }

    // Param is passed by value, moved
    pub fn set_filters(&mut self, v: ::std::string::String) {
        self.filters = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_filters(&mut self) -> &mut ::std::string::String {
        &mut self.filters
    }

    // Take field
    pub fn take_filters(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.filters, ::std::string::String::new())
    }
}

impl ::protobuf::Message for SetRowIndexFilters {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.filters)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.filters.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.filters);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.filters.is_empty() {
            os.write_string(1, &self.filters)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> SetRowIndexFilters {
        SetRowIndexFilters::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "filters",
                |m: &SetRowIndexFilters| { &m.filters },
                |m: &mut SetRowIndexFilters| { &mut m.filters },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<SetRowIndexFilters>(
                "SetRowIndexFilters",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static SetRowIndexFilters {
        static instance: ::protobuf::rt::LazyV2<SetRowIndexFilters> = ::protobuf::rt::LazyV2::INIT;
        instance.get(SetRowIndexFilters::new)
    }
}

impl ::protobuf::Clear for SetRowIndexFilters {
    fn clear(&mut self) {
        self.filters.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for SetRowIndexFilters {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for SetRowIndexFilters {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
#[cfg_attr(feature = "with-serde", derive(::serde::Serialize, ::serde::Deserialize))]
pub struct SetRowRegexFilter {
    // message fields
    pub filter: ::std::string::String,
    // special fields
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub unknown_fields: ::protobuf::UnknownFields,
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a SetRowRegexFilter {
    fn default() -> &'a SetRowRegexFilter {
        <SetRowRegexFilter as ::protobuf::Message>::default_instance()
    }
}

impl SetRowRegexFilter {
    pub fn new() -> SetRowRegexFilter {
        ::std::default::Default::default()
    }

    // string filter = 1;


    pub fn get_filter(&self) -> &str {
        &self.filter
    }
    pub fn clear_filter(&mut self) {
        self.filter.clear();
    }

    // Param is passed by value, moved
    pub fn set_filter(&mut self, v: ::std::string::String) {
        self.filter = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_filter(&mut self) -> &mut ::std::string::String {
        &mut self.filter
    }

    // Take field
    pub fn take_filter(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.filter, ::std::string::String::new())
    }
}

impl ::protobuf::Message for SetRowRegexFilter {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.filter)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.filter.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.filter);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.filter.is_empty() {
            os.write_string(1, &self.filter)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> SetRowRegexFilter {
        SetRowRegexFilter::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "filter",
                |m: &SetRowRegexFilter| { &m.filter },
                |m: &mut SetRowRegexFilter| { &mut m.filter },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<SetRowRegexFilter>(
                "SetRowRegexFilter",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static SetRowRegexFilter {
        static instance: ::protobuf::rt::LazyV2<SetRowRegexFilter> = ::protobuf::rt::LazyV2::INIT;
        instance.get(SetRowRegexFilter::new)
    }
}

impl ::protobuf::Clear for SetRowRegexFilter {
    fn clear(&mut self) {
        self.filter.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for SetRowRegexFilter {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for SetRowRegexFilter {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
#[cfg_attr(feature = "with-serde", derive(::serde::Serialize, ::serde::Deserialize))]
pub struct SetRowSeparators {
    // message fields
    pub separators: ::protobuf::RepeatedField<::std::string::String>,
    // special fields
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub unknown_fields: ::protobuf::UnknownFields,
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a SetRowSeparators {
    fn default() -> &'a SetRowSeparators {
        <SetRowSeparators as ::protobuf::Message>::default_instance()
    }
}

impl SetRowSeparators {
    pub fn new() -> SetRowSeparators {
        ::std::default::Default::default()
    }

    // repeated string separators = 1;


    pub fn get_separators(&self) -> &[::std::string::String] {
        &self.separators
    }
    pub fn clear_separators(&mut self) {
        self.separators.clear();
    }

    // Param is passed by value, moved
    pub fn set_separators(&mut self, v: ::protobuf::RepeatedField<::std::string::String>) {
        self.separators = v;
    }

    // Mutable pointer to the field.
    pub fn mut_separators(&mut self) -> &mut ::protobuf::RepeatedField<::std::string::String> {
        &mut self.separators
    }

    // Take field
    pub fn take_separators(&mut self) -> ::protobuf::RepeatedField<::std::string::String> {
        ::std::mem::replace(&mut self.separators, ::protobuf::RepeatedField::new())
    }
}

impl ::protobuf::Message for SetRowSeparators {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_repeated_string_into(wire_type, is, &mut self.separators)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        for value in &self.separators {
            my_size += ::protobuf::rt::string_size(1, &value);
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        for v in &self.separators {
            os.write_string(1, &v)?;
        };
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> SetRowSeparators {
        SetRowSeparators::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "separators",
                |m: &SetRowSeparators| { &m.separators },
                |m: &mut SetRowSeparators| { &mut m.separators },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<SetRowSeparators>(
                "SetRowSeparators",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static SetRowSeparators {
        static instance: ::protobuf::rt::LazyV2<SetRowSeparators> = ::protobuf::rt::LazyV2::INIT;
        instance.get(SetRowSeparators::new)
    }
}

impl ::protobuf::Clear for SetRowSeparators {
    fn clear(&mut self) {
        self.separators.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for SetRowSeparators {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for SetRowSeparators {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
#[cfg_attr(feature = "with-serde", derive(::serde::Serialize, ::serde::Deserialize))]
pub struct SetColumnIndexFilters {
    // message fields
    pub filters: ::std::string::String,
    // special fields
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub unknown_fields: ::protobuf::UnknownFields,
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a SetColumnIndexFilters {
    fn default() -> &'a SetColumnIndexFilters {
        <SetColumnIndexFilters as ::protobuf::Message>::default_instance()
    }
}

impl SetColumnIndexFilters {
    pub fn new() -> SetColumnIndexFilters {
        ::std::default::Default::default()
    }

    // string filters = 1;


    pub fn get_filters(&self) -> &str {
        &self.filters
    }
    pub fn clear_filters(&mut self) {
        self.filters.clear();
    }

    // Param is passed by value, moved
    pub fn set_filters(&mut self, v: ::std::string::String) {
        self.filters = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_filters(&mut self) -> &mut ::std::string::String {
        &mut self.filters
    }

    // Take field
    pub fn take_filters(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.filters, ::std::string::String::new())
    }
}

impl ::protobuf::Message for SetColumnIndexFilters {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.filters)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.filters.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.filters);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.filters.is_empty() {
            os.write_string(1, &self.filters)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> SetColumnIndexFilters {
        SetColumnIndexFilters::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "filters",
                |m: &SetColumnIndexFilters| { &m.filters },
                |m: &mut SetColumnIndexFilters| { &mut m.filters },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<SetColumnIndexFilters>(
                "SetColumnIndexFilters",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static SetColumnIndexFilters {
        static instance: ::protobuf::rt::LazyV2<SetColumnIndexFilters> = ::protobuf::rt::LazyV2::INIT;
        instance.get(SetColumnIndexFilters::new)
    }
}

impl ::protobuf::Clear for SetColumnIndexFilters {
    fn clear(&mut self) {
        self.filters.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for SetColumnIndexFilters {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for SetColumnIndexFilters {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
#[cfg_attr(feature = "with-serde", derive(::serde::Serialize, ::serde::Deserialize))]
pub struct SetColumnRegexFilter {
    // message fields
    pub filter: ::std::string::String,
    // special fields
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub unknown_fields: ::protobuf::UnknownFields,
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a SetColumnRegexFilter {
    fn default() -> &'a SetColumnRegexFilter {
        <SetColumnRegexFilter as ::protobuf::Message>::default_instance()
    }
}

impl SetColumnRegexFilter {
    pub fn new() -> SetColumnRegexFilter {
        ::std::default::Default::default()
    }

    // string filter = 1;


    pub fn get_filter(&self) -> &str {
        &self.filter
    }
    pub fn clear_filter(&mut self) {
        self.filter.clear();
    }

    // Param is passed by value, moved
    pub fn set_filter(&mut self, v: ::std::string::String) {
        self.filter = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_filter(&mut self) -> &mut ::std::string::String {
        &mut self.filter
    }

    // Take field
    pub fn take_filter(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.filter, ::std::string::String::new())
    }
}

impl ::protobuf::Message for SetColumnRegexFilter {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.filter)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.filter.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.filter);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.filter.is_empty() {
            os.write_string(1, &self.filter)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> SetColumnRegexFilter {
        SetColumnRegexFilter::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "filter",
                |m: &SetColumnRegexFilter| { &m.filter },
                |m: &mut SetColumnRegexFilter| { &mut m.filter },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<SetColumnRegexFilter>(
                "SetColumnRegexFilter",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static SetColumnRegexFilter {
        static instance: ::protobuf::rt::LazyV2<SetColumnRegexFilter> = ::protobuf::rt::LazyV2::INIT;
        instance.get(SetColumnRegexFilter::new)
    }
}

impl ::protobuf::Clear for SetColumnRegexFilter {
    fn clear(&mut self) {
        self.filter.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for SetColumnRegexFilter {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for SetColumnRegexFilter {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
#[cfg_attr(feature = "with-serde", derive(::serde::Serialize, ::serde::Deserialize))]
pub struct SetColumnSeparators {
    // message fields
    pub separators: ::protobuf::RepeatedField<::std::string::String>,
    // special fields
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub unknown_fields: ::protobuf::UnknownFields,
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a SetColumnSeparators {
    fn default() -> &'a SetColumnSeparators {
        <SetColumnSeparators as ::protobuf::Message>::default_instance()
    }
}

impl SetColumnSeparators {
    pub fn new() -> SetColumnSeparators {
        ::std::default::Default::default()
    }

    // repeated string separators = 1;


    pub fn get_separators(&self) -> &[::std::string::String] {
        &self.separators
    }
    pub fn clear_separators(&mut self) {
        self.separators.clear();
    }

    // Param is passed by value, moved
    pub fn set_separators(&mut self, v: ::protobuf::RepeatedField<::std::string::String>) {
        self.separators = v;
    }

    // Mutable pointer to the field.
    pub fn mut_separators(&mut self) -> &mut ::protobuf::RepeatedField<::std::string::String> {
        &mut self.separators
    }

    // Take field
    pub fn take_separators(&mut self) -> ::protobuf::RepeatedField<::std::string::String> {
        ::std::mem::replace(&mut self.separators, ::protobuf::RepeatedField::new())
    }
}

impl ::protobuf::Message for SetColumnSeparators {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_repeated_string_into(wire_type, is, &mut self.separators)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        for value in &self.separators {
            my_size += ::protobuf::rt::string_size(1, &value);
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        for v in &self.separators {
            os.write_string(1, &v)?;
        };
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> SetColumnSeparators {
        SetColumnSeparators::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "separators",
                |m: &SetColumnSeparators| { &m.separators },
                |m: &mut SetColumnSeparators| { &mut m.separators },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<SetColumnSeparators>(
                "SetColumnSeparators",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static SetColumnSeparators {
        static instance: ::protobuf::rt::LazyV2<SetColumnSeparators> = ::protobuf::rt::LazyV2::INIT;
        instance.get(SetColumnSeparators::new)
    }
}

impl ::protobuf::Clear for SetColumnSeparators {
    fn clear(&mut self) {
        self.separators.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for SetColumnSeparators {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for SetColumnSeparators {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
#[cfg_attr(feature = "with-serde", derive(::serde::Serialize, ::serde::Deserialize))]
pub struct FromClient {
    // message oneof groups
    pub inner: ::std::option::Option<FromClient_oneof_inner>,
    // special fields
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub unknown_fields: ::protobuf::UnknownFields,
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a FromClient {
    fn default() -> &'a FromClient {
        <FromClient as ::protobuf::Message>::default_instance()
    }
}

#[derive(Clone,PartialEq,Debug)]
#[cfg_attr(feature = "with-serde", derive(::serde::Serialize, ::serde::Deserialize))]
pub enum FromClient_oneof_inner {
    initialize(Initialize),
    set_row_index_filters(SetRowIndexFilters),
    set_row_regex_filter(SetRowRegexFilter),
    set_row_separators(SetRowSeparators),
    set_column_index_filters(SetColumnIndexFilters),
    set_column_regex_filter(SetColumnRegexFilter),
    set_column_separators(SetColumnSeparators),
}

impl FromClient {
    pub fn new() -> FromClient {
        ::std::default::Default::default()
    }

    // .Initialize initialize = 1;


    pub fn get_initialize(&self) -> &Initialize {
        match self.inner {
            ::std::option::Option::Some(FromClient_oneof_inner::initialize(ref v)) => v,
            _ => <Initialize as ::protobuf::Message>::default_instance(),
        }
    }
    pub fn clear_initialize(&mut self) {
        self.inner = ::std::option::Option::None;
    }

    pub fn has_initialize(&self) -> bool {
        match self.inner {
            ::std::option::Option::Some(FromClient_oneof_inner::initialize(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_initialize(&mut self, v: Initialize) {
        self.inner = ::std::option::Option::Some(FromClient_oneof_inner::initialize(v))
    }

    // Mutable pointer to the field.
    pub fn mut_initialize(&mut self) -> &mut Initialize {
        if let ::std::option::Option::Some(FromClient_oneof_inner::initialize(_)) = self.inner {
        } else {
            self.inner = ::std::option::Option::Some(FromClient_oneof_inner::initialize(Initialize::new()));
        }
        match self.inner {
            ::std::option::Option::Some(FromClient_oneof_inner::initialize(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_initialize(&mut self) -> Initialize {
        if self.has_initialize() {
            match self.inner.take() {
                ::std::option::Option::Some(FromClient_oneof_inner::initialize(v)) => v,
                _ => panic!(),
            }
        } else {
            Initialize::new()
        }
    }

    // .SetRowIndexFilters set_row_index_filters = 2;


    pub fn get_set_row_index_filters(&self) -> &SetRowIndexFilters {
        match self.inner {
            ::std::option::Option::Some(FromClient_oneof_inner::set_row_index_filters(ref v)) => v,
            _ => <SetRowIndexFilters as ::protobuf::Message>::default_instance(),
        }
    }
    pub fn clear_set_row_index_filters(&mut self) {
        self.inner = ::std::option::Option::None;
    }

    pub fn has_set_row_index_filters(&self) -> bool {
        match self.inner {
            ::std::option::Option::Some(FromClient_oneof_inner::set_row_index_filters(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_set_row_index_filters(&mut self, v: SetRowIndexFilters) {
        self.inner = ::std::option::Option::Some(FromClient_oneof_inner::set_row_index_filters(v))
    }

    // Mutable pointer to the field.
    pub fn mut_set_row_index_filters(&mut self) -> &mut SetRowIndexFilters {
        if let ::std::option::Option::Some(FromClient_oneof_inner::set_row_index_filters(_)) = self.inner {
        } else {
            self.inner = ::std::option::Option::Some(FromClient_oneof_inner::set_row_index_filters(SetRowIndexFilters::new()));
        }
        match self.inner {
            ::std::option::Option::Some(FromClient_oneof_inner::set_row_index_filters(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_set_row_index_filters(&mut self) -> SetRowIndexFilters {
        if self.has_set_row_index_filters() {
            match self.inner.take() {
                ::std::option::Option::Some(FromClient_oneof_inner::set_row_index_filters(v)) => v,
                _ => panic!(),
            }
        } else {
            SetRowIndexFilters::new()
        }
    }

    // .SetRowRegexFilter set_row_regex_filter = 3;


    pub fn get_set_row_regex_filter(&self) -> &SetRowRegexFilter {
        match self.inner {
            ::std::option::Option::Some(FromClient_oneof_inner::set_row_regex_filter(ref v)) => v,
            _ => <SetRowRegexFilter as ::protobuf::Message>::default_instance(),
        }
    }
    pub fn clear_set_row_regex_filter(&mut self) {
        self.inner = ::std::option::Option::None;
    }

    pub fn has_set_row_regex_filter(&self) -> bool {
        match self.inner {
            ::std::option::Option::Some(FromClient_oneof_inner::set_row_regex_filter(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_set_row_regex_filter(&mut self, v: SetRowRegexFilter) {
        self.inner = ::std::option::Option::Some(FromClient_oneof_inner::set_row_regex_filter(v))
    }

    // Mutable pointer to the field.
    pub fn mut_set_row_regex_filter(&mut self) -> &mut SetRowRegexFilter {
        if let ::std::option::Option::Some(FromClient_oneof_inner::set_row_regex_filter(_)) = self.inner {
        } else {
            self.inner = ::std::option::Option::Some(FromClient_oneof_inner::set_row_regex_filter(SetRowRegexFilter::new()));
        }
        match self.inner {
            ::std::option::Option::Some(FromClient_oneof_inner::set_row_regex_filter(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_set_row_regex_filter(&mut self) -> SetRowRegexFilter {
        if self.has_set_row_regex_filter() {
            match self.inner.take() {
                ::std::option::Option::Some(FromClient_oneof_inner::set_row_regex_filter(v)) => v,
                _ => panic!(),
            }
        } else {
            SetRowRegexFilter::new()
        }
    }

    // .SetRowSeparators set_row_separators = 4;


    pub fn get_set_row_separators(&self) -> &SetRowSeparators {
        match self.inner {
            ::std::option::Option::Some(FromClient_oneof_inner::set_row_separators(ref v)) => v,
            _ => <SetRowSeparators as ::protobuf::Message>::default_instance(),
        }
    }
    pub fn clear_set_row_separators(&mut self) {
        self.inner = ::std::option::Option::None;
    }

    pub fn has_set_row_separators(&self) -> bool {
        match self.inner {
            ::std::option::Option::Some(FromClient_oneof_inner::set_row_separators(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_set_row_separators(&mut self, v: SetRowSeparators) {
        self.inner = ::std::option::Option::Some(FromClient_oneof_inner::set_row_separators(v))
    }

    // Mutable pointer to the field.
    pub fn mut_set_row_separators(&mut self) -> &mut SetRowSeparators {
        if let ::std::option::Option::Some(FromClient_oneof_inner::set_row_separators(_)) = self.inner {
        } else {
            self.inner = ::std::option::Option::Some(FromClient_oneof_inner::set_row_separators(SetRowSeparators::new()));
        }
        match self.inner {
            ::std::option::Option::Some(FromClient_oneof_inner::set_row_separators(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_set_row_separators(&mut self) -> SetRowSeparators {
        if self.has_set_row_separators() {
            match self.inner.take() {
                ::std::option::Option::Some(FromClient_oneof_inner::set_row_separators(v)) => v,
                _ => panic!(),
            }
        } else {
            SetRowSeparators::new()
        }
    }

    // .SetColumnIndexFilters set_column_index_filters = 5;


    pub fn get_set_column_index_filters(&self) -> &SetColumnIndexFilters {
        match self.inner {
            ::std::option::Option::Some(FromClient_oneof_inner::set_column_index_filters(ref v)) => v,
            _ => <SetColumnIndexFilters as ::protobuf::Message>::default_instance(),
        }
    }
    pub fn clear_set_column_index_filters(&mut self) {
        self.inner = ::std::option::Option::None;
    }

    pub fn has_set_column_index_filters(&self) -> bool {
        match self.inner {
            ::std::option::Option::Some(FromClient_oneof_inner::set_column_index_filters(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_set_column_index_filters(&mut self, v: SetColumnIndexFilters) {
        self.inner = ::std::option::Option::Some(FromClient_oneof_inner::set_column_index_filters(v))
    }

    // Mutable pointer to the field.
    pub fn mut_set_column_index_filters(&mut self) -> &mut SetColumnIndexFilters {
        if let ::std::option::Option::Some(FromClient_oneof_inner::set_column_index_filters(_)) = self.inner {
        } else {
            self.inner = ::std::option::Option::Some(FromClient_oneof_inner::set_column_index_filters(SetColumnIndexFilters::new()));
        }
        match self.inner {
            ::std::option::Option::Some(FromClient_oneof_inner::set_column_index_filters(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_set_column_index_filters(&mut self) -> SetColumnIndexFilters {
        if self.has_set_column_index_filters() {
            match self.inner.take() {
                ::std::option::Option::Some(FromClient_oneof_inner::set_column_index_filters(v)) => v,
                _ => panic!(),
            }
        } else {
            SetColumnIndexFilters::new()
        }
    }

    // .SetColumnRegexFilter set_column_regex_filter = 6;


    pub fn get_set_column_regex_filter(&self) -> &SetColumnRegexFilter {
        match self.inner {
            ::std::option::Option::Some(FromClient_oneof_inner::set_column_regex_filter(ref v)) => v,
            _ => <SetColumnRegexFilter as ::protobuf::Message>::default_instance(),
        }
    }
    pub fn clear_set_column_regex_filter(&mut self) {
        self.inner = ::std::option::Option::None;
    }

    pub fn has_set_column_regex_filter(&self) -> bool {
        match self.inner {
            ::std::option::Option::Some(FromClient_oneof_inner::set_column_regex_filter(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_set_column_regex_filter(&mut self, v: SetColumnRegexFilter) {
        self.inner = ::std::option::Option::Some(FromClient_oneof_inner::set_column_regex_filter(v))
    }

    // Mutable pointer to the field.
    pub fn mut_set_column_regex_filter(&mut self) -> &mut SetColumnRegexFilter {
        if let ::std::option::Option::Some(FromClient_oneof_inner::set_column_regex_filter(_)) = self.inner {
        } else {
            self.inner = ::std::option::Option::Some(FromClient_oneof_inner::set_column_regex_filter(SetColumnRegexFilter::new()));
        }
        match self.inner {
            ::std::option::Option::Some(FromClient_oneof_inner::set_column_regex_filter(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_set_column_regex_filter(&mut self) -> SetColumnRegexFilter {
        if self.has_set_column_regex_filter() {
            match self.inner.take() {
                ::std::option::Option::Some(FromClient_oneof_inner::set_column_regex_filter(v)) => v,
                _ => panic!(),
            }
        } else {
            SetColumnRegexFilter::new()
        }
    }

    // .SetColumnSeparators set_column_separators = 7;


    pub fn get_set_column_separators(&self) -> &SetColumnSeparators {
        match self.inner {
            ::std::option::Option::Some(FromClient_oneof_inner::set_column_separators(ref v)) => v,
            _ => <SetColumnSeparators as ::protobuf::Message>::default_instance(),
        }
    }
    pub fn clear_set_column_separators(&mut self) {
        self.inner = ::std::option::Option::None;
    }

    pub fn has_set_column_separators(&self) -> bool {
        match self.inner {
            ::std::option::Option::Some(FromClient_oneof_inner::set_column_separators(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_set_column_separators(&mut self, v: SetColumnSeparators) {
        self.inner = ::std::option::Option::Some(FromClient_oneof_inner::set_column_separators(v))
    }

    // Mutable pointer to the field.
    pub fn mut_set_column_separators(&mut self) -> &mut SetColumnSeparators {
        if let ::std::option::Option::Some(FromClient_oneof_inner::set_column_separators(_)) = self.inner {
        } else {
            self.inner = ::std::option::Option::Some(FromClient_oneof_inner::set_column_separators(SetColumnSeparators::new()));
        }
        match self.inner {
            ::std::option::Option::Some(FromClient_oneof_inner::set_column_separators(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_set_column_separators(&mut self) -> SetColumnSeparators {
        if self.has_set_column_separators() {
            match self.inner.take() {
                ::std::option::Option::Some(FromClient_oneof_inner::set_column_separators(v)) => v,
                _ => panic!(),
            }
        } else {
            SetColumnSeparators::new()
        }
    }
}

impl ::protobuf::Message for FromClient {
    fn is_initialized(&self) -> bool {
        if let Some(FromClient_oneof_inner::initialize(ref v)) = self.inner {
            if !v.is_initialized() {
                return false;
            }
        }
        if let Some(FromClient_oneof_inner::set_row_index_filters(ref v)) = self.inner {
            if !v.is_initialized() {
                return false;
            }
        }
        if let Some(FromClient_oneof_inner::set_row_regex_filter(ref v)) = self.inner {
            if !v.is_initialized() {
                return false;
            }
        }
        if let Some(FromClient_oneof_inner::set_row_separators(ref v)) = self.inner {
            if !v.is_initialized() {
                return false;
            }
        }
        if let Some(FromClient_oneof_inner::set_column_index_filters(ref v)) = self.inner {
            if !v.is_initialized() {
                return false;
            }
        }
        if let Some(FromClient_oneof_inner::set_column_regex_filter(ref v)) = self.inner {
            if !v.is_initialized() {
                return false;
            }
        }
        if let Some(FromClient_oneof_inner::set_column_separators(ref v)) = self.inner {
            if !v.is_initialized() {
                return false;
            }
        }
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.inner = ::std::option::Option::Some(FromClient_oneof_inner::initialize(is.read_message()?));
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.inner = ::std::option::Option::Some(FromClient_oneof_inner::set_row_index_filters(is.read_message()?));
                },
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.inner = ::std::option::Option::Some(FromClient_oneof_inner::set_row_regex_filter(is.read_message()?));
                },
                4 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.inner = ::std::option::Option::Some(FromClient_oneof_inner::set_row_separators(is.read_message()?));
                },
                5 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.inner = ::std::option::Option::Some(FromClient_oneof_inner::set_column_index_filters(is.read_message()?));
                },
                6 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.inner = ::std::option::Option::Some(FromClient_oneof_inner::set_column_regex_filter(is.read_message()?));
                },
                7 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.inner = ::std::option::Option::Some(FromClient_oneof_inner::set_column_separators(is.read_message()?));
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let ::std::option::Option::Some(ref v) = self.inner {
            match v {
                &FromClient_oneof_inner::initialize(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
                },
                &FromClient_oneof_inner::set_row_index_filters(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
                },
                &FromClient_oneof_inner::set_row_regex_filter(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
                },
                &FromClient_oneof_inner::set_row_separators(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
                },
                &FromClient_oneof_inner::set_column_index_filters(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
                },
                &FromClient_oneof_inner::set_column_regex_filter(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
                },
                &FromClient_oneof_inner::set_column_separators(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
                },
            };
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if let ::std::option::Option::Some(ref v) = self.inner {
            match v {
                &FromClient_oneof_inner::initialize(ref v) => {
                    os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
                    os.write_raw_varint32(v.get_cached_size())?;
                    v.write_to_with_cached_sizes(os)?;
                },
                &FromClient_oneof_inner::set_row_index_filters(ref v) => {
                    os.write_tag(2, ::protobuf::wire_format::WireTypeLengthDelimited)?;
                    os.write_raw_varint32(v.get_cached_size())?;
                    v.write_to_with_cached_sizes(os)?;
                },
                &FromClient_oneof_inner::set_row_regex_filter(ref v) => {
                    os.write_tag(3, ::protobuf::wire_format::WireTypeLengthDelimited)?;
                    os.write_raw_varint32(v.get_cached_size())?;
                    v.write_to_with_cached_sizes(os)?;
                },
                &FromClient_oneof_inner::set_row_separators(ref v) => {
                    os.write_tag(4, ::protobuf::wire_format::WireTypeLengthDelimited)?;
                    os.write_raw_varint32(v.get_cached_size())?;
                    v.write_to_with_cached_sizes(os)?;
                },
                &FromClient_oneof_inner::set_column_index_filters(ref v) => {
                    os.write_tag(5, ::protobuf::wire_format::WireTypeLengthDelimited)?;
                    os.write_raw_varint32(v.get_cached_size())?;
                    v.write_to_with_cached_sizes(os)?;
                },
                &FromClient_oneof_inner::set_column_regex_filter(ref v) => {
                    os.write_tag(6, ::protobuf::wire_format::WireTypeLengthDelimited)?;
                    os.write_raw_varint32(v.get_cached_size())?;
                    v.write_to_with_cached_sizes(os)?;
                },
                &FromClient_oneof_inner::set_column_separators(ref v) => {
                    os.write_tag(7, ::protobuf::wire_format::WireTypeLengthDelimited)?;
                    os.write_raw_varint32(v.get_cached_size())?;
                    v.write_to_with_cached_sizes(os)?;
                },
            };
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> FromClient {
        FromClient::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_singular_message_accessor::<_, Initialize>(
                "initialize",
                FromClient::has_initialize,
                FromClient::get_initialize,
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_message_accessor::<_, SetRowIndexFilters>(
                "set_row_index_filters",
                FromClient::has_set_row_index_filters,
                FromClient::get_set_row_index_filters,
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_message_accessor::<_, SetRowRegexFilter>(
                "set_row_regex_filter",
                FromClient::has_set_row_regex_filter,
                FromClient::get_set_row_regex_filter,
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_message_accessor::<_, SetRowSeparators>(
                "set_row_separators",
                FromClient::has_set_row_separators,
                FromClient::get_set_row_separators,
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_message_accessor::<_, SetColumnIndexFilters>(
                "set_column_index_filters",
                FromClient::has_set_column_index_filters,
                FromClient::get_set_column_index_filters,
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_message_accessor::<_, SetColumnRegexFilter>(
                "set_column_regex_filter",
                FromClient::has_set_column_regex_filter,
                FromClient::get_set_column_regex_filter,
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_message_accessor::<_, SetColumnSeparators>(
                "set_column_separators",
                FromClient::has_set_column_separators,
                FromClient::get_set_column_separators,
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<FromClient>(
                "FromClient",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static FromClient {
        static instance: ::protobuf::rt::LazyV2<FromClient> = ::protobuf::rt::LazyV2::INIT;
        instance.get(FromClient::new)
    }
}

impl ::protobuf::Clear for FromClient {
    fn clear(&mut self) {
        self.inner = ::std::option::Option::None;
        self.inner = ::std::option::Option::None;
        self.inner = ::std::option::Option::None;
        self.inner = ::std::option::Option::None;
        self.inner = ::std::option::Option::None;
        self.inner = ::std::option::Option::None;
        self.inner = ::std::option::Option::None;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for FromClient {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for FromClient {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x11definitions.proto\"3\n\x0fUnexpectedError\x12\x20\n\x0bdescription\
    \x18\x01\x20\x01(\tR\x0bdescription\"n\n\nFromServer\x12\x18\n\x06output\
    \x18\x01\x20\x01(\x0cH\0R\x06output\x12=\n\x10unexpected_error\x18\x02\
    \x20\x01(\x0b2\x10.UnexpectedErrorH\0R\x0funexpectedErrorB\x07\n\x05inne\
    r\"\x98\x02\n\nInitialize\x12*\n\x11row_index_filters\x18\x01\x20\x01(\t\
    R\x0frowIndexFilters\x12(\n\x10row_regex_filter\x18\x02\x20\x01(\tR\x0er\
    owRegexFilter\x12%\n\x0erow_separators\x18\x03\x20\x03(\tR\rrowSeparator\
    s\x120\n\x14column_index_filters\x18\x04\x20\x01(\tR\x12columnIndexFilte\
    rs\x12.\n\x13column_regex_filter\x18\x05\x20\x01(\tR\x11columnRegexFilte\
    r\x12+\n\x11column_separators\x18\x06\x20\x03(\tR\x10columnSeparators\".\
    \n\x12SetRowIndexFilters\x12\x18\n\x07filters\x18\x01\x20\x01(\tR\x07fil\
    ters\"+\n\x11SetRowRegexFilter\x12\x16\n\x06filter\x18\x01\x20\x01(\tR\
    \x06filter\"2\n\x10SetRowSeparators\x12\x1e\n\nseparators\x18\x01\x20\
    \x03(\tR\nseparators\"1\n\x15SetColumnIndexFilters\x12\x18\n\x07filters\
    \x18\x01\x20\x01(\tR\x07filters\".\n\x14SetColumnRegexFilter\x12\x16\n\
    \x06filter\x18\x01\x20\x01(\tR\x06filter\"5\n\x13SetColumnSeparators\x12\
    \x1e\n\nseparators\x18\x01\x20\x03(\tR\nseparators\"\x87\x04\n\nFromClie\
    nt\x12-\n\ninitialize\x18\x01\x20\x01(\x0b2\x0b.InitializeH\0R\ninitiali\
    ze\x12H\n\x15set_row_index_filters\x18\x02\x20\x01(\x0b2\x13.SetRowIndex\
    FiltersH\0R\x12setRowIndexFilters\x12E\n\x14set_row_regex_filter\x18\x03\
    \x20\x01(\x0b2\x12.SetRowRegexFilterH\0R\x11setRowRegexFilter\x12A\n\x12\
    set_row_separators\x18\x04\x20\x01(\x0b2\x11.SetRowSeparatorsH\0R\x10set\
    RowSeparators\x12Q\n\x18set_column_index_filters\x18\x05\x20\x01(\x0b2\
    \x16.SetColumnIndexFiltersH\0R\x15setColumnIndexFilters\x12N\n\x17set_co\
    lumn_regex_filter\x18\x06\x20\x01(\x0b2\x15.SetColumnRegexFilterH\0R\x14\
    setColumnRegexFilter\x12J\n\x15set_column_separators\x18\x07\x20\x01(\
    \x0b2\x14.SetColumnSeparatorsH\0R\x13setColumnSeparatorsB\x07\n\x05inner\
    b\x06proto3\
";

static file_descriptor_proto_lazy: ::protobuf::rt::LazyV2<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::LazyV2::INIT;

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    file_descriptor_proto_lazy.get(|| {
        parse_descriptor_proto()
    })
}
